import 'package:flutter/material.dart';
import 'package:klasio/config/app_colors.dart';
import 'package:klasio/domain/entities/color.dart';
import 'package:klasio/domain/entities/icon.dart';

final List<ColorOption> colorOptions = [
  ColorOption(
    option: AppColors.folderBlue,
    bgOption: AppColors.folderBlueLight,
  ),
  ColorOption(
    option: AppColors.folderGreen,
    bgOption: AppColors.folderGreenLight,
  ),
  ColorOption(
    option: AppColors.folderOrange,
    bgOption: AppColors.folderOrangeLight,
  ),
  ColorOption(
    option: AppColors.folderPurple,
    bgOption: AppColors.folderPurpleLight,
  ),
  ColorOption(
    option: AppColors.folderPink,
    bgOption: AppColors.folderPinkLight,
  ),
  ColorOption(
    option: AppColors.folderYellow,
    bgOption: AppColors.folderYellowLight,
  ),
  ColorOption(option: Color(0xFF14B8A6), bgOption: Color(0xFFCCFBF1)),
  ColorOption(option: Color(0xFF6366F1), bgOption: Color(0xFFE0E7FF)),
  ColorOption(option: Color(0xFFF43F5E), bgOption: Color(0xFFFFE4E6)),
  ColorOption(option: Color(0xFF10B981), bgOption: Color(0xFFD1FAE5)),
  ColorOption(option: Color(0xFF8B5CF6), bgOption: Color(0xFFEDE9FE)),
  ColorOption(option: Color(0xFF06B6D4), bgOption: Color(0xFFCFFAFE)),
  ColorOption(option: Color(0xFF84CC16), bgOption: Color(0xFFECFCCB)),
  ColorOption(option: Color(0xFFD946EF), bgOption: Color(0xFFFAE8FF)),
  ColorOption(option: Color(0xFF64748B), bgOption: Color(0xFFF1F5F9)),
  ColorOption(option: Color(0xFFE11D48), bgOption: Color(0xFFFFE4E6)),
];

final List<IconOption> iconOptions = [
  IconOption(option: Icons.folder),
  IconOption(option: Icons.cloud),
  IconOption(option: Icons.calendar_today),
  IconOption(option: Icons.book),
  IconOption(option: Icons.bookmark),
  IconOption(option: Icons.money),
  IconOption(option: Icons.school),
  IconOption(option: Icons.work),
  IconOption(option: Icons.star),
  IconOption(option: Icons.email),
  IconOption(option: Icons.message),
  IconOption(option: Icons.call),
  IconOption(option: Icons.video_call),
  IconOption(option: Icons.photo),
  IconOption(option: Icons.camera),
  IconOption(option: Icons.videocam),
  IconOption(option: Icons.music_note),
  IconOption(option: Icons.headset),
  IconOption(option: Icons.shopping_cart),
  IconOption(option: Icons.local_offer),
  IconOption(option: Icons.restaurant),
  IconOption(option: Icons.wallet),
  IconOption(option: Icons.menu_book_rounded),
  IconOption(option: Icons.science_rounded),
  IconOption(option: Icons.calculate_rounded),
  IconOption(option: Icons.biotech_rounded),
  IconOption(option: Icons.psychology_rounded),
  IconOption(option: Icons.history_edu_rounded),
  IconOption(option: Icons.translate_rounded),
  IconOption(option: Icons.laptop_chromebook_rounded),
  IconOption(option: Icons.code_rounded),
  IconOption(option: Icons.draw_rounded),
  IconOption(option: Icons.palette_rounded),
  IconOption(option: Icons.auto_stories_rounded),
  IconOption(option: Icons.assignment_rounded),
  IconOption(option: Icons.quiz_rounded),
  IconOption(option: Icons.lightbulb_outline_rounded),
  IconOption(option: Icons.sports_soccer_rounded),
  IconOption(option: Icons.fitness_center_rounded),
  IconOption(option: Icons.architecture_rounded),
  IconOption(option: Icons.public_rounded),
  IconOption(option: Icons.local_hospital_rounded),
  IconOption(option: Icons.emoji_events_rounded),
  IconOption(option: Icons.edit_note_rounded),
  IconOption(option: Icons.storage_rounded),
  IconOption(option: Icons.extension_rounded),
  IconOption(option: Icons.analytics_rounded),
  IconOption(option: Icons.terminal_rounded),
  IconOption(option: Icons.medical_services_rounded),
  IconOption(option: Icons.brush_rounded),
];
